package appbatalhanaval;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import clientebatalhanaval.ClienteBatalhaNaval;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ComponentListener;
import java.util.jar.Attributes.Name;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jogobatalhanaval.AcaoBatalhaNaval;
import jogobatalhanaval.JogadaBatalhaNaval;
import jogobatalhanaval.JogadorBatalhaNaval;
import projetocliente.ProjetoCliente;
import mensagem.Endereco;

/**
 *
 * @author Fernando
 */
public class TelaJogo extends javax.swing.JFrame {

    private ServidorApp servidor;
    private JogadorBatalhaNaval jogador;
    private int port;

    public ServidorApp getServidor() {
        return servidor;
    }

    public void setServidor(ServidorApp servidor) {
        this.servidor = servidor;
    }


    public JogadorBatalhaNaval getJogador() {
        return jogador;
    }

    public void setJogador(JogadorBatalhaNaval jogador) {
        this.jogador = jogador;
    }

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port = port;
    }
    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
    }
    
    private void jogar(int casa) {
        AcaoBatalhaNaval acao = new AcaoBatalhaNaval(casa);
        JogadaBatalhaNaval jogada = new JogadaBatalhaNaval(acao);
        jogada.setJogador(jogador);
        jogada.jogar(acao);
        jogada.setEnderecoServidor(new Endereco("192.168.107.220", 864));
        jogada.setEnderecoJogador(new Endereco(servidor.getHost(), servidor.getPort()));
        jogada.setEnderecoDestinatario(jogada.getEnderecoServidor());
        ClienteBatalhaNaval cliente = new ClienteBatalhaNaval();
        cliente.enviarMensagem(jogada);
    }
    
    public String getNomeJogador() {
        return jtfNome.getText().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jbCasa0 = new javax.swing.JButton();
        jbCasa1 = new javax.swing.JButton();
        jbCasa2 = new javax.swing.JButton();
        jbCasa3 = new javax.swing.JButton();
        jbCasa4 = new javax.swing.JButton();
        jbCasa5 = new javax.swing.JButton();
        jbCasa6 = new javax.swing.JButton();
        jbCasa7 = new javax.swing.JButton();
        jbCasa8 = new javax.swing.JButton();
        jbConectar = new javax.swing.JButton();
        jbCasa9 = new javax.swing.JButton();
        jbCasa10 = new javax.swing.JButton();
        jbCasa11 = new javax.swing.JButton();
        jbCasa12 = new javax.swing.JButton();
        jbCasa13 = new javax.swing.JButton();
        jbCasa14 = new javax.swing.JButton();
        jbCasa15 = new javax.swing.JButton();
        jbCasa16 = new javax.swing.JButton();
        jbCasa17 = new javax.swing.JButton();
        jbCasa18 = new javax.swing.JButton();
        jbCasa19 = new javax.swing.JButton();
        jbCasa20 = new javax.swing.JButton();
        jbCasa21 = new javax.swing.JButton();
        jbCasa22 = new javax.swing.JButton();
        jbCasa23 = new javax.swing.JButton();
        jbCasa24 = new javax.swing.JButton();
        jbCasa25 = new javax.swing.JButton();
        jbCasa26 = new javax.swing.JButton();
        jbCasa27 = new javax.swing.JButton();
        jbCasa28 = new javax.swing.JButton();
        jbCasa29 = new javax.swing.JButton();
        jbCasa30 = new javax.swing.JButton();
        jbCasa31 = new javax.swing.JButton();
        jbCasa32 = new javax.swing.JButton();
        jbCasa33 = new javax.swing.JButton();
        jbCasa34 = new javax.swing.JButton();
        jbCasa35 = new javax.swing.JButton();
        jbCasa36 = new javax.swing.JButton();
        jbCasa37 = new javax.swing.JButton();
        jbCasa38 = new javax.swing.JButton();
        jbCasa39 = new javax.swing.JButton();
        jbCasa40 = new javax.swing.JButton();
        jbCasa41 = new javax.swing.JButton();
        jbCasa42 = new javax.swing.JButton();
        jbCasa43 = new javax.swing.JButton();
        jbCasa44 = new javax.swing.JButton();
        jbCasa45 = new javax.swing.JButton();
        jbCasa46 = new javax.swing.JButton();
        jbCasa47 = new javax.swing.JButton();
        jbCasa48 = new javax.swing.JButton();
        jbCasa49 = new javax.swing.JButton();
        jbCasa50 = new javax.swing.JButton();
        jbCasa51 = new javax.swing.JButton();
        jbCasa52 = new javax.swing.JButton();
        jbCasa53 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlPontuacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jbCasa0.setName("casa0"); // NOI18N
        jbCasa0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa0ActionPerformed(evt);
            }
        });

        jbCasa1.setName("casa1"); // NOI18N
        jbCasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa1ActionPerformed(evt);
            }
        });

        jbCasa2.setName("casa2"); // NOI18N
        jbCasa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa2ActionPerformed(evt);
            }
        });

        jbCasa3.setName("casa3"); // NOI18N
        jbCasa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa3ActionPerformed(evt);
            }
        });

        jbCasa4.setName("casa4"); // NOI18N
        jbCasa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa4ActionPerformed(evt);
            }
        });

        jbCasa5.setName("casa5"); // NOI18N
        jbCasa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa5ActionPerformed(evt);
            }
        });

        jbCasa6.setName("casa6"); // NOI18N
        jbCasa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa6ActionPerformed(evt);
            }
        });

        jbCasa7.setName("casa7"); // NOI18N
        jbCasa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa7ActionPerformed(evt);
            }
        });

        jbCasa8.setName("casa8"); // NOI18N
        jbCasa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa8ActionPerformed(evt);
            }
        });

        jbConectar.setText("Conectar");
        jbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConectarActionPerformed(evt);
            }
        });

        jbCasa9.setName("casa9"); // NOI18N
        jbCasa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa9ActionPerformed(evt);
            }
        });

        jbCasa10.setName("casa10"); // NOI18N
        jbCasa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa10ActionPerformed(evt);
            }
        });

        jbCasa11.setName("casa11"); // NOI18N
        jbCasa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa11ActionPerformed(evt);
            }
        });

        jbCasa12.setName("casa12"); // NOI18N
        jbCasa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa12ActionPerformed(evt);
            }
        });

        jbCasa13.setName("casa13"); // NOI18N
        jbCasa13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa13ActionPerformed(evt);
            }
        });

        jbCasa14.setName("casa14"); // NOI18N
        jbCasa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa14ActionPerformed(evt);
            }
        });

        jbCasa15.setName("casa15"); // NOI18N
        jbCasa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa15ActionPerformed(evt);
            }
        });

        jbCasa16.setName("casa16"); // NOI18N
        jbCasa16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa16ActionPerformed(evt);
            }
        });

        jbCasa17.setName("casa17"); // NOI18N
        jbCasa17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa17ActionPerformed(evt);
            }
        });

        jbCasa18.setName("casa18"); // NOI18N
        jbCasa18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa18ActionPerformed(evt);
            }
        });

        jbCasa19.setName("casa19"); // NOI18N
        jbCasa19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa19ActionPerformed(evt);
            }
        });

        jbCasa20.setName("casa20"); // NOI18N
        jbCasa20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa20ActionPerformed(evt);
            }
        });

        jbCasa21.setName("casa21"); // NOI18N
        jbCasa21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa21ActionPerformed(evt);
            }
        });

        jbCasa22.setName("casa22"); // NOI18N
        jbCasa22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa22ActionPerformed(evt);
            }
        });

        jbCasa23.setName("casa23"); // NOI18N
        jbCasa23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa23ActionPerformed(evt);
            }
        });

        jbCasa24.setName("casa24"); // NOI18N
        jbCasa24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa24ActionPerformed(evt);
            }
        });

        jbCasa25.setName("casa25"); // NOI18N
        jbCasa25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa25ActionPerformed(evt);
            }
        });

        jbCasa26.setName("casa26"); // NOI18N
        jbCasa26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa26ActionPerformed(evt);
            }
        });

        jbCasa27.setName("casa27"); // NOI18N
        jbCasa27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa27ActionPerformed(evt);
            }
        });

        jbCasa28.setName("casa28"); // NOI18N
        jbCasa28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa28ActionPerformed(evt);
            }
        });

        jbCasa29.setName("casa29"); // NOI18N
        jbCasa29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa29ActionPerformed(evt);
            }
        });

        jbCasa30.setName("casa30"); // NOI18N
        jbCasa30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa30ActionPerformed(evt);
            }
        });

        jbCasa31.setName("casa31"); // NOI18N
        jbCasa31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa31ActionPerformed(evt);
            }
        });

        jbCasa32.setName("casa32"); // NOI18N
        jbCasa32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa32ActionPerformed(evt);
            }
        });

        jbCasa33.setName("casa33"); // NOI18N
        jbCasa33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa33ActionPerformed(evt);
            }
        });

        jbCasa34.setName("casa34"); // NOI18N
        jbCasa34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa34ActionPerformed(evt);
            }
        });

        jbCasa35.setName("casa35"); // NOI18N
        jbCasa35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa35ActionPerformed(evt);
            }
        });

        jbCasa36.setName("casa36"); // NOI18N
        jbCasa36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa36ActionPerformed(evt);
            }
        });

        jbCasa37.setName("casa37"); // NOI18N
        jbCasa37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa37ActionPerformed(evt);
            }
        });

        jbCasa38.setName("casa38"); // NOI18N
        jbCasa38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa38ActionPerformed(evt);
            }
        });

        jbCasa39.setName("casa39"); // NOI18N
        jbCasa39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa39ActionPerformed(evt);
            }
        });

        jbCasa40.setName("casa40"); // NOI18N
        jbCasa40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa40ActionPerformed(evt);
            }
        });

        jbCasa41.setName("casa41"); // NOI18N
        jbCasa41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa41ActionPerformed(evt);
            }
        });

        jbCasa42.setName("casa42"); // NOI18N
        jbCasa42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa42ActionPerformed(evt);
            }
        });

        jbCasa43.setName("casa43"); // NOI18N
        jbCasa43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa43ActionPerformed(evt);
            }
        });

        jbCasa44.setName("casa44"); // NOI18N
        jbCasa44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa44ActionPerformed(evt);
            }
        });

        jbCasa45.setName("casa45"); // NOI18N
        jbCasa45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa45ActionPerformed(evt);
            }
        });

        jbCasa46.setName("casa46"); // NOI18N
        jbCasa46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa46ActionPerformed(evt);
            }
        });

        jbCasa47.setName("casa47"); // NOI18N
        jbCasa47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa47ActionPerformed(evt);
            }
        });

        jbCasa48.setName("casa48"); // NOI18N
        jbCasa48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa48ActionPerformed(evt);
            }
        });

        jbCasa49.setName("casa49"); // NOI18N
        jbCasa49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa49ActionPerformed(evt);
            }
        });

        jbCasa50.setName("casa50"); // NOI18N
        jbCasa50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa50ActionPerformed(evt);
            }
        });

        jbCasa51.setName("casa51"); // NOI18N
        jbCasa51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa51ActionPerformed(evt);
            }
        });

        jbCasa52.setName("casa52"); // NOI18N
        jbCasa52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa52ActionPerformed(evt);
            }
        });

        jbCasa53.setName("casa53"); // NOI18N
        jbCasa53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCasa53ActionPerformed(evt);
            }
        });

        jLabel2.setText("Pontuação:");

        jlPontuacao.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jtfNome))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbCasa9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbCasa18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa25, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbCasa27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa29, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa30, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa31, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa32, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa33, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa34, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa35, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbCasa36, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa37, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa38, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa39, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa40, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa41, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa42, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa43, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCasa44, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 162, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbCasa45, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa46, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa47, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa48, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa49, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa50, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa51, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa52, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa53, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jbConectar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbCasa0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCasa8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlPontuacao)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbCasa0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbCasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbCasa2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbCasa6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jlPontuacao))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jbConectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCasa3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbCasa9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jbCasa15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbCasa12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbCasa18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jbCasa24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa25, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbCasa21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbCasa27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa29, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jbCasa33, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa34, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa35, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbCasa30, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa31, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa32, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbCasa36, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa37, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa38, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jbCasa42, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa43, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa44, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbCasa39, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa40, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa41, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbCasa45, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa46, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCasa47, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jbCasa51, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa52, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa53, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbCasa48, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa49, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCasa50, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCasa0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa0ActionPerformed
        jogar(0);
    }//GEN-LAST:event_jbCasa0ActionPerformed

    private void jbCasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa1ActionPerformed
        jogar(1);
    }//GEN-LAST:event_jbCasa1ActionPerformed

    private void jbCasa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa2ActionPerformed
        jogar(2);
    }//GEN-LAST:event_jbCasa2ActionPerformed

    private void jbCasa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa3ActionPerformed
        jogar(3);
    }//GEN-LAST:event_jbCasa3ActionPerformed

    private void jbCasa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa4ActionPerformed
        jogar(4);
    }//GEN-LAST:event_jbCasa4ActionPerformed

    private void jbCasa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa5ActionPerformed
        jogar(5);
    }//GEN-LAST:event_jbCasa5ActionPerformed

    private void jbCasa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa6ActionPerformed
        jogar(6);
    }//GEN-LAST:event_jbCasa6ActionPerformed

    private void jbCasa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa7ActionPerformed
        jogar(7);
    }//GEN-LAST:event_jbCasa7ActionPerformed

    private void jbCasa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa8ActionPerformed
        jogar(8);
    }//GEN-LAST:event_jbCasa8ActionPerformed

    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConectarActionPerformed
        jtfNome.disable();
        jbConectar.disable();
        jogador = new JogadorBatalhaNaval();
        jogador.setNome(jtfNome.getText().toString());
        Endereco enderecoServidor = new Endereco("192.168.107.220", 864);
        Endereco enderecoJogador = new Endereco(servidor.getHost(), servidor.getPort());
        jogador.setEnderecoServidor(enderecoServidor);
        jogador.setEnderecoJogador(enderecoJogador);
        jogador.setEnderecoDestinatario(enderecoServidor);
        ClientApp cliente = new ClientApp();
        cliente.enviarMensagem(jogador);
    }//GEN-LAST:event_jbConectarActionPerformed

    private void jbCasa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa9ActionPerformed
        jogar(9);
    }//GEN-LAST:event_jbCasa9ActionPerformed

    private void jbCasa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa10ActionPerformed
        jogar(10);
    }//GEN-LAST:event_jbCasa10ActionPerformed

    private void jbCasa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa11ActionPerformed
        jogar(11);
    }//GEN-LAST:event_jbCasa11ActionPerformed

    private void jbCasa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa12ActionPerformed
        jogar(12);
    }//GEN-LAST:event_jbCasa12ActionPerformed

    private void jbCasa13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa13ActionPerformed
        jogar(13);
    }//GEN-LAST:event_jbCasa13ActionPerformed

    private void jbCasa14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa14ActionPerformed
        jogar(14);
    }//GEN-LAST:event_jbCasa14ActionPerformed

    private void jbCasa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa15ActionPerformed
        jogar(15);
    }//GEN-LAST:event_jbCasa15ActionPerformed

    private void jbCasa16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa16ActionPerformed
        jogar(16);
    }//GEN-LAST:event_jbCasa16ActionPerformed

    private void jbCasa17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa17ActionPerformed
        jogar(17);
    }//GEN-LAST:event_jbCasa17ActionPerformed

    private void jbCasa18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa18ActionPerformed
        jogar(18);
    }//GEN-LAST:event_jbCasa18ActionPerformed

    private void jbCasa19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa19ActionPerformed
        jogar(19);
    }//GEN-LAST:event_jbCasa19ActionPerformed

    private void jbCasa20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa20ActionPerformed
        jogar(20);
    }//GEN-LAST:event_jbCasa20ActionPerformed

    private void jbCasa21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa21ActionPerformed
        jogar(21);
    }//GEN-LAST:event_jbCasa21ActionPerformed

    private void jbCasa22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa22ActionPerformed
        jogar(22);
    }//GEN-LAST:event_jbCasa22ActionPerformed

    private void jbCasa23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa23ActionPerformed
        jogar(23);
    }//GEN-LAST:event_jbCasa23ActionPerformed

    private void jbCasa24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa24ActionPerformed
        jogar(24);
    }//GEN-LAST:event_jbCasa24ActionPerformed

    private void jbCasa25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa25ActionPerformed
        jogar(25);
    }//GEN-LAST:event_jbCasa25ActionPerformed

    private void jbCasa26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa26ActionPerformed
        jogar(26);
    }//GEN-LAST:event_jbCasa26ActionPerformed

    private void jbCasa27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa27ActionPerformed
        jogar(27);
    }//GEN-LAST:event_jbCasa27ActionPerformed

    private void jbCasa28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa28ActionPerformed
        jogar(28);
    }//GEN-LAST:event_jbCasa28ActionPerformed

    private void jbCasa29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa29ActionPerformed
        jogar(29);
    }//GEN-LAST:event_jbCasa29ActionPerformed

    private void jbCasa30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa30ActionPerformed
        jogar(30);
    }//GEN-LAST:event_jbCasa30ActionPerformed

    private void jbCasa31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa31ActionPerformed
        jogar(31);
    }//GEN-LAST:event_jbCasa31ActionPerformed

    private void jbCasa32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa32ActionPerformed
        jogar(32);
    }//GEN-LAST:event_jbCasa32ActionPerformed

    private void jbCasa33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa33ActionPerformed
        jogar(33);
    }//GEN-LAST:event_jbCasa33ActionPerformed

    private void jbCasa34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa34ActionPerformed
        jogar(34);
    }//GEN-LAST:event_jbCasa34ActionPerformed

    private void jbCasa35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa35ActionPerformed
        jogar(35);
    }//GEN-LAST:event_jbCasa35ActionPerformed

    private void jbCasa36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa36ActionPerformed
        jogar(36);
    }//GEN-LAST:event_jbCasa36ActionPerformed

    private void jbCasa37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa37ActionPerformed
        jogar(37);
    }//GEN-LAST:event_jbCasa37ActionPerformed

    private void jbCasa38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa38ActionPerformed
        jogar(38);
    }//GEN-LAST:event_jbCasa38ActionPerformed

    private void jbCasa39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa39ActionPerformed
        jogar(39);
    }//GEN-LAST:event_jbCasa39ActionPerformed

    private void jbCasa40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa40ActionPerformed
        jogar(40);
    }//GEN-LAST:event_jbCasa40ActionPerformed

    private void jbCasa41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa41ActionPerformed
        jogar(41);
    }//GEN-LAST:event_jbCasa41ActionPerformed

    private void jbCasa42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa42ActionPerformed
        jogar(42);
    }//GEN-LAST:event_jbCasa42ActionPerformed

    private void jbCasa43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa43ActionPerformed
        jogar(43);
    }//GEN-LAST:event_jbCasa43ActionPerformed

    private void jbCasa44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa44ActionPerformed
        jogar(44);
    }//GEN-LAST:event_jbCasa44ActionPerformed

    private void jbCasa45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa45ActionPerformed
        jogar(45);
    }//GEN-LAST:event_jbCasa45ActionPerformed

    private void jbCasa46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa46ActionPerformed
        jogar(46);
    }//GEN-LAST:event_jbCasa46ActionPerformed

    private void jbCasa47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa47ActionPerformed
        jogar(47);
    }//GEN-LAST:event_jbCasa47ActionPerformed

    private void jbCasa48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa48ActionPerformed
        jogar(48);
    }//GEN-LAST:event_jbCasa48ActionPerformed

    private void jbCasa49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa49ActionPerformed
        jogar(49);
    }//GEN-LAST:event_jbCasa49ActionPerformed

    private void jbCasa50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa50ActionPerformed
        jogar(50);
    }//GEN-LAST:event_jbCasa50ActionPerformed

    private void jbCasa51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa51ActionPerformed
        jogar(51);
    }//GEN-LAST:event_jbCasa51ActionPerformed

    private void jbCasa52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa52ActionPerformed
        jogar(52);
    }//GEN-LAST:event_jbCasa52ActionPerformed

    private void jbCasa53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCasa53ActionPerformed
        jogar(53);
    }//GEN-LAST:event_jbCasa53ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbCasa0;
    private javax.swing.JButton jbCasa1;
    private javax.swing.JButton jbCasa10;
    private javax.swing.JButton jbCasa11;
    private javax.swing.JButton jbCasa12;
    private javax.swing.JButton jbCasa13;
    private javax.swing.JButton jbCasa14;
    private javax.swing.JButton jbCasa15;
    private javax.swing.JButton jbCasa16;
    private javax.swing.JButton jbCasa17;
    private javax.swing.JButton jbCasa18;
    private javax.swing.JButton jbCasa19;
    private javax.swing.JButton jbCasa2;
    private javax.swing.JButton jbCasa20;
    private javax.swing.JButton jbCasa21;
    private javax.swing.JButton jbCasa22;
    private javax.swing.JButton jbCasa23;
    private javax.swing.JButton jbCasa24;
    private javax.swing.JButton jbCasa25;
    private javax.swing.JButton jbCasa26;
    private javax.swing.JButton jbCasa27;
    private javax.swing.JButton jbCasa28;
    private javax.swing.JButton jbCasa29;
    private javax.swing.JButton jbCasa3;
    private javax.swing.JButton jbCasa30;
    private javax.swing.JButton jbCasa31;
    private javax.swing.JButton jbCasa32;
    private javax.swing.JButton jbCasa33;
    private javax.swing.JButton jbCasa34;
    private javax.swing.JButton jbCasa35;
    private javax.swing.JButton jbCasa36;
    private javax.swing.JButton jbCasa37;
    private javax.swing.JButton jbCasa38;
    private javax.swing.JButton jbCasa39;
    private javax.swing.JButton jbCasa4;
    private javax.swing.JButton jbCasa40;
    private javax.swing.JButton jbCasa41;
    private javax.swing.JButton jbCasa42;
    private javax.swing.JButton jbCasa43;
    private javax.swing.JButton jbCasa44;
    private javax.swing.JButton jbCasa45;
    private javax.swing.JButton jbCasa46;
    private javax.swing.JButton jbCasa47;
    private javax.swing.JButton jbCasa48;
    private javax.swing.JButton jbCasa49;
    private javax.swing.JButton jbCasa5;
    private javax.swing.JButton jbCasa50;
    private javax.swing.JButton jbCasa51;
    private javax.swing.JButton jbCasa52;
    private javax.swing.JButton jbCasa53;
    private javax.swing.JButton jbCasa6;
    private javax.swing.JButton jbCasa7;
    private javax.swing.JButton jbCasa8;
    private javax.swing.JButton jbCasa9;
    private javax.swing.JButton jbConectar;
    private javax.swing.JLabel jlPontuacao;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
    
    private synchronized Component getComponentePeloNome(Container c, String nomeComponente) {
        Component[] comps = c.getComponents();
        for (int i = 0; i < comps.length; i++) {
            Component componente = comps[i];
            if (componente.getName() != null) {
                if (componente.getName().equals(nomeComponente)) {
                    return componente;
                }
            }
            Component retorno = getComponentePeloNome((Container) comps[i], nomeComponente);
            if (retorno != null) {
                return retorno;
            }
        }
        return null;
    }
    
    public void iniciarJogo() {
        jbConectar.disable();
    }
    
    public synchronized void renderizar(JogadaBatalhaNaval jogada) {
        System.out.println("Renderizando");
        AcaoBatalhaNaval acaoBatalhaNaval = (AcaoBatalhaNaval) jogada.getAcao();
        JButton botao = ((JButton) getComponentePeloNome(this, "casa" + String.valueOf(acaoBatalhaNaval.getCasa())));
        if (botao != null) {
            botao.setText(String.valueOf(acaoBatalhaNaval.getElemento()));
            botao.disable();
        } else {
            JOptionPane.showMessageDialog(null, "erro");
        }
    }
    
    public synchronized void atualizarPontuacao(JogadaBatalhaNaval jogada) {    
        AcaoBatalhaNaval acaoBatalhaNaval = (AcaoBatalhaNaval) jogada.getAcao();    
        jlPontuacao.setText(String.valueOf(Integer.parseInt(jlPontuacao.getText()) + acaoBatalhaNaval.getElemento()));
    }

}
